### ISSUE TITLE
Failed to execute child process "/usr/lib/gvfs/gvfsd-trash" (No such file or directory)

### ISSUE THREAD

**Issue by langkatnetwork** [xentaoslinux/pengembangan#2]
Unable to mount location
Failed to execute child process "/usr/lib/gvfs/gvfsd-trash" (No such file or directory)

**Comment by langkatnetwork** [comment]
Solved issues kalian bisa Download file gvfsd-trash di bawah ini
buka terminal xentaos : 
```bash
sudo wget https://github.com/xentaoslinux/pengembangan/raw/master/issues/gvfs/gvfsd-trash -P /usr/lib/gvfs/
sudo chmod 777 /usr/lib/gvfs/gvfsd-trash
```
skrng trash bisa di buka kembali

**Comment by dindinG41TR3** [comment]
[Solved] Failed to execute child process "/usr/lib/gvfs/gvfsd-trash" (No such file or directory)
